# Generated by Django 6.0.4 on 2026-04-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('roomno', models.IntegerField()),
                ('rollno', models.IntegerField()),
            ],
        ),
    ]
