# Generated by Django 6.0.4 on 2026-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
    ]
